$ErrorActionPreference = 'Stop'
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '../..')).Path
Push-Location $repoRoot
try {
    # Search text only. Excel packages and other binary artifacts are explicitly excluded.
    $filters = @('--hidden', '--no-ignore', '-g', '!.git/**', '-g', '!**/.git/**',
        '-g', '!outputs/shift-duration-reconciliation/**', '-g', '!*.xlsx', '-g', '!*.xls',
        '-g', '!*.xlsm', '-g', '!*.xlsb', '-g', '!*.xltx', '-g', '!*.xltm',
        '-g', '!*.twbx', '-g', '!*.hyper', '-g', '!*.mez')
    $pattern = '(?i)duration|shift[ _.-]*(length|hrs|hours)|effective[ _.-]*(shift|availability)|meal[ _.-]*break|unpaid|paid[ _.-]*hours|direct care|res.*effective.*ratio|intervaleffectiveratio|allocatedeffort|timeworked|ordinaryworkwk|stdrosterdays|\bFTE\b|\b7[.,][56]\b|(?<![\w.])0?\.(5|93[0-9]*|95)\b|\b(8|456|450|480|38|76)\b|half.hour|30.minute|break time'
    $events = @(& rg --json --pcre2 @filters -e $pattern .)
    if ($LASTEXITCODE -gt 1) { throw 'Repository search failed.' }
    $rows = @($events | ForEach-Object {
        $event = $_ | ConvertFrom-Json
        if ($event.type -eq 'match') {
            $path = $event.data.path.text -replace '^\.\\', '' -replace '\\', '/'
            $classification = if ($path -match 'SyncPathMigration-Backups|\.old$|\.bak|_backup| copy\.') { 'Backup or variant' }
                elseif ($path -match '^outputs/') { 'Prior diagnostic artifact' }
                elseif ($path -match '^Workflows/.*/Diagnostics/|^scripts/') { 'Diagnostic or tooling' }
                elseif ($path -match '\.md$') { 'Documentation' }
                elseif ($path -match '\.m$|\.pq$') { 'Repository M source (workbook parity unverified)' }
                else { 'Other text' }
            [pscustomobject]@{ Path = $path; Line = $event.data.line_number; Classification = $classification;
                Text = $event.data.lines.text.TrimEnd() }
        }
    })
    # Query labels are navigation aids, not an M parser or proof of execution.
    foreach ($fileGroup in ($rows | Where-Object { $_.Path -match '\.(m|pq)$' } | Group-Object Path)) {
        $sourceLines = @(Get-Content -LiteralPath $fileGroup.Name)
        $query = '(file header)'
        $matchLines = @{}
        foreach ($row in $fileGroup.Group) { $matchLines[[int]$row.Line] = $row }
        for ($i = 0; $i -lt $sourceLines.Count; $i++) {
            if ($sourceLines[$i] -match '^shared\s+(.+?)\s*=') { $query = $Matches[1] }
            if ($matchLines.ContainsKey($i + 1)) {
                $matchLines[$i + 1] | Add-Member -NotePropertyName Query -NotePropertyValue $query
            }
        }
    }
    $summary = [ordered]@{
        Generated = (Get-Date -Format o)
        Scope = 'Working-tree text, including ignored/hidden text, backups and diagnostic artifacts; excludes .git and Excel packages. No workbook inspection or execution.'
        Pattern = $pattern
        MatchingFiles = @($rows.Path | Sort-Object -Unique).Count
        MatchingLines = $rows.Count
        Files = @($rows | Group-Object Path | Sort-Object Name | ForEach-Object {
            [pscustomobject]@{ Path = $_.Name; MatchingLines = $_.Count; Classification = $_.Group[0].Classification }
        })
    }
    $rows | ConvertTo-Json -Depth 5 | Set-Content -LiteralPath (Join-Path $PSScriptRoot 'matches.json') -Encoding UTF8
    $summary | ConvertTo-Json -Depth 5 | Set-Content -LiteralPath (Join-Path $PSScriptRoot 'coverage.json') -Encoding UTF8
    $index = [Collections.Generic.List[string]]::new()
    $index.Add('# Shift-duration search index')
    $index.Add('')
    $index.Add('Generated by collect-evidence.ps1. These are broad search matches, including incidental numbers, comments and unused queries. See README.md for assessed findings and matches.json for exact lines. Query names are derived from the preceding shared declaration, not from execution. Paths are relative to the repository root.')
    foreach ($fileGroup in ($rows | Group-Object Path | Sort-Object Name)) {
        $index.Add('')
        $index.Add('## ' + $fileGroup.Name)
        $index.Add('')
        $index.Add($fileGroup.Group[0].Classification + '; ' + $fileGroup.Count + ' matching lines.')
        $index.Add('')
        if ($fileGroup.Name -match '\.(m|pq)$') {
            foreach ($queryGroup in ($fileGroup.Group | Group-Object Query)) {
                $lineNumbers = ($queryGroup.Group.Line | Sort-Object) -join ', '
                $index.Add('- `' + $queryGroup.Name + '`: lines ' + $lineNumbers + '.')
            }
        } else {
            $index.Add('Lines: ' + (($fileGroup.Group.Line | Sort-Object) -join ', ') + '.')
        }
    }
    $index | Set-Content -LiteralPath (Join-Path $PSScriptRoot 'index.md') -Encoding UTF8
    [pscustomobject]$summary | Select-Object MatchingFiles,MatchingLines | Format-List
    $summary.Files | Group-Object Classification | Select-Object Name,Count | Format-Table
} finally { Pop-Location }
