gantt
    title Current forecast - elapsed 00 00 49
    dateFormat YYYY-MM-DD HH:mm:ss.SSS
    axisFormat %H:%M:%S
    todayMarker off
    section BD/D2
    %% Predecessors: BD/Intervals, BD/DemandInput, BD/Settings
    BD/DemandIntervals attempt 1 Forecast :task1, 2000-01-01 00:00:00.000, 2000-01-01 00:00:45.261
    section TE/D2
    %% Predecessors: TE/Intervals, TE/DemandInput, TE/Settings
    TE/DemandIntervals attempt 1 Forecast :task2, 2000-01-01 00:00:00.000, 2000-01-01 00:00:44.661
    section JH-RY/D2
    %% Predecessors: JH-RY/Intervals, JH-RY/DemandInput, JH-RY/Settings
    JH-RY/DemandIntervals attempt 1 Forecast :task3, 2000-01-01 00:00:00.000, 2000-01-01 00:00:49.320
