gantt
    title Current 20260925-152227-1bc9ae5f Completed - elapsed 00 02 06 - peak 1
    dateFormat YYYY-MM-DD HH:mm:ss.SSS
    axisFormat %H:%M:%S
    todayMarker off
    section Org/O2
    %% Predecessors: Org/EffortAll, Org/StaffAll
    Org/Outcomes attempt 1 Completed :done, task1, 2000-01-01 00:00:00.409, 2000-01-01 00:00:40.071
    %% Predecessors: Org/Outcomes
    Org/Inefficiencies attempt 1 Completed :done, task2, 2000-01-01 00:00:40.093, 2000-01-01 00:01:27.319
    section Org/O5
    %% Predecessors: Org/Cost, Org/HistoryRead, Org/Inefficiencies
    Org/Reporting attempt 1 Completed :done, task3, 2000-01-01 00:01:27.341, 2000-01-01 00:02:06.915
