gantt
    title Current forecast - elapsed 00 19 37
    dateFormat YYYY-MM-DD HH:mm:ss.SSS
    axisFormat %H:%M:%S
    todayMarker off
    section BD/A1
    %% Predecessors:
    BD/AllocationInput attempt 1 Forecast :task1, 2000-01-01 00:00:00.000, 2000-01-01 00:00:51.581
    section BD/S1
    %% Predecessors: BD/AllocationInput
    BD/Settings attempt 1 Forecast :task2, 2000-01-01 00:00:51.581, 2000-01-01 00:01:39.638
    section BD/D1
    %% Predecessors: BD/Settings
    BD/DemandMaster attempt 1 Forecast :task3, 2000-01-01 00:01:39.638, 2000-01-01 00:04:51.326
    %% Predecessors: BD/DemandMaster, BD/Settings
    BD/DemandInput attempt 1 Forecast :task4, 2000-01-01 00:04:51.326, 2000-01-01 00:05:41.640
    section BD/C1
    %% Predecessors: BD/AllocationInput, BD/Settings
    BD/Workers attempt 1 Forecast :task5, 2000-01-01 00:01:39.638, 2000-01-01 00:02:45.699
    %% Predecessors: BD/Workers, BD/AllocationInput, BD/Settings
    BD/Availability attempt 1 Forecast :task6, 2000-01-01 00:02:45.699, 2000-01-01 00:06:18.874
    %% Predecessors: BD/Availability, BD/Workers, BD/AllocationInput, BD/Settings
    BD/Staff attempt 1 Forecast :task7, 2000-01-01 00:06:18.874, 2000-01-01 00:07:06.997
    section BD/D2
    %% Predecessors: BD/AllocationInput, BD/DemandInput, BD/Settings
    BD/Intervals attempt 1 Forecast :task8, 2000-01-01 00:05:41.640, 2000-01-01 00:06:28.643
    %% Predecessors: BD/Intervals, BD/DemandInput, BD/Settings
    BD/DemandIntervals attempt 1 Forecast :task9, 2000-01-01 00:06:28.643, 2000-01-01 00:07:15.685
    %% Predecessors: BD/DemandIntervals, BD/Settings
    BD/Demand attempt 1 Forecast :task10, 2000-01-01 00:07:15.685, 2000-01-01 00:08:02.825
    section BD/A2
    %% Predecessors: BD/Intervals, BD/AllocationInput, BD/Settings
    BD/Shifts attempt 1 Forecast :task11, 2000-01-01 00:06:28.643, 2000-01-01 00:08:50.301
    %% Predecessors: BD/Shifts, BD/Settings
    BD/ShiftAverage attempt 1 Forecast :task12, 2000-01-01 00:08:50.301, 2000-01-01 00:10:23.345
    section BD/A3
    %% Predecessors: BD/ShiftAverage, BD/AllocationInput, BD/Settings
    BD/Allocation attempt 1 Forecast :task13, 2000-01-01 00:10:23.345, 2000-01-01 00:11:15.245
    %% Predecessors: BD/Allocation, BD/Settings
    BD/Distribution attempt 1 Forecast :task14, 2000-01-01 00:11:15.245, 2000-01-01 00:12:08.941
    %% Predecessors: BD/Distribution, BD/Settings
    BD/MultiRole attempt 1 Forecast :task15, 2000-01-01 00:12:08.941, 2000-01-01 00:12:54.143
    section BD/C2 AIN
    %% Predecessors: BD/Demand, BD/Staff, BD/Availability, BD/ShiftAverage, BD/Settings
    BD/Role AIN/1 attempt 1 Forecast :task16, 2000-01-01 00:10:23.345, 2000-01-01 00:12:02.636
    %% Predecessors: BD/Demand, BD/Staff, BD/Availability, BD/ShiftAverage, BD/Settings, BD/Role:AIN/1
    BD/Role AIN/2 attempt 1 Forecast :task17, 2000-01-01 00:12:02.636, 2000-01-01 00:12:54.194
    %% Predecessors: BD/Demand, BD/Staff, BD/Availability, BD/ShiftAverage, BD/Settings, BD/Role:AIN/2
    BD/Role AIN/3 attempt 1 Forecast :task18, 2000-01-01 00:12:54.194, 2000-01-01 00:14:04.489
    section BD/C2 RN
    %% Predecessors: BD/Demand, BD/Staff, BD/Availability, BD/ShiftAverage, BD/Settings
    BD/Role RN/1 attempt 1 Forecast :task19, 2000-01-01 00:10:23.345, 2000-01-01 00:11:49.963
    %% Predecessors: BD/Demand, BD/Staff, BD/Availability, BD/ShiftAverage, BD/Settings, BD/Role:RN/1
    BD/Role RN/2 attempt 1 Forecast :task20, 2000-01-01 00:11:49.963, 2000-01-01 00:12:34.406
    %% Predecessors: BD/Demand, BD/Staff, BD/Availability, BD/ShiftAverage, BD/Settings, BD/Role:RN/2
    BD/Role RN/3 attempt 1 Forecast :task21, 2000-01-01 00:12:34.406, 2000-01-01 00:13:24.874
    section BD/C2 EN
    %% Predecessors: BD/Demand, BD/Staff, BD/Availability, BD/ShiftAverage, BD/Settings
    BD/Role EN/1 attempt 1 Forecast :task22, 2000-01-01 00:10:23.345, 2000-01-01 00:11:47.047
    %% Predecessors: BD/Demand, BD/Staff, BD/Availability, BD/ShiftAverage, BD/Settings, BD/Role:EN/1
    BD/Role EN/2 attempt 1 Forecast :task23, 2000-01-01 00:11:47.047, 2000-01-01 00:12:33.017
    %% Predecessors: BD/Demand, BD/Staff, BD/Availability, BD/ShiftAverage, BD/Settings, BD/Role:EN/2
    BD/Role EN/3 attempt 1 Forecast :task24, 2000-01-01 00:12:33.017, 2000-01-01 00:13:22.774
    section BD/U4
    %% Predecessors: BD/Role:AIN/3, BD/Role:EN/3, BD/Role:RN/3, BD/Demand, BD/Staff, BD/Availability, BD/Settings
    BD/Capacity attempt 1 Forecast :task25, 2000-01-01 00:14:04.489, 2000-01-01 00:14:48.002
    %% Predecessors: BD/Capacity, BD/Demand, BD/Allocation, BD/Distribution, BD/MultiRole, BD/Staff, BD/Settings
    BD/Effort attempt 1 Forecast :task26, 2000-01-01 00:14:48.002, 2000-01-01 00:15:32.030
    section TE/A1
    %% Predecessors:
    TE/AllocationInput attempt 1 Forecast :task27, 2000-01-01 00:00:00.000, 2000-01-01 00:00:49.923
    section TE/S1
    %% Predecessors: TE/AllocationInput
    TE/Settings attempt 1 Forecast :task28, 2000-01-01 00:00:49.923, 2000-01-01 00:01:35.644
    section TE/D1
    %% Predecessors: TE/Settings
    TE/DemandMaster attempt 1 Forecast :task29, 2000-01-01 00:01:35.644, 2000-01-01 00:04:39.485
    %% Predecessors: TE/DemandMaster, TE/Settings
    TE/DemandInput attempt 1 Forecast :task30, 2000-01-01 00:04:39.485, 2000-01-01 00:05:30.386
    section TE/C1
    %% Predecessors: TE/AllocationInput, TE/Settings
    TE/Workers attempt 1 Forecast :task31, 2000-01-01 00:01:35.644, 2000-01-01 00:02:42.103
    %% Predecessors: TE/Workers, TE/AllocationInput, TE/Settings
    TE/Availability attempt 1 Forecast :task32, 2000-01-01 00:02:42.103, 2000-01-01 00:05:10.271
    %% Predecessors: TE/Availability, TE/Workers, TE/AllocationInput, TE/Settings
    TE/Staff attempt 1 Forecast :task33, 2000-01-01 00:05:10.271, 2000-01-01 00:05:58.053
    section TE/D2
    %% Predecessors: TE/AllocationInput, TE/DemandInput, TE/Settings
    TE/Intervals attempt 1 Forecast :task34, 2000-01-01 00:05:30.386, 2000-01-01 00:06:17.483
    %% Predecessors: TE/Intervals, TE/DemandInput, TE/Settings
    TE/DemandIntervals attempt 1 Forecast :task35, 2000-01-01 00:06:17.483, 2000-01-01 00:07:01.250
    %% Predecessors: TE/DemandIntervals, TE/Settings
    TE/Demand attempt 1 Forecast :task36, 2000-01-01 00:07:01.250, 2000-01-01 00:07:47.554
    section TE/A2
    %% Predecessors: TE/Intervals, TE/AllocationInput, TE/Settings
    TE/Shifts attempt 1 Forecast :task37, 2000-01-01 00:06:17.483, 2000-01-01 00:07:32.616
    %% Predecessors: TE/Shifts, TE/Settings
    TE/ShiftAverage attempt 1 Forecast :task38, 2000-01-01 00:07:32.616, 2000-01-01 00:08:41.911
    section TE/A3
    %% Predecessors: TE/ShiftAverage, TE/AllocationInput, TE/Settings
    TE/Allocation attempt 1 Forecast :task39, 2000-01-01 00:08:41.911, 2000-01-01 00:09:25.787
    %% Predecessors: TE/Allocation, TE/Settings
    TE/Distribution attempt 1 Forecast :task40, 2000-01-01 00:09:25.787, 2000-01-01 00:10:19.832
    %% Predecessors: TE/Distribution, TE/Settings
    TE/MultiRole attempt 1 Forecast :task41, 2000-01-01 00:10:19.832, 2000-01-01 00:11:11.196
    section TE/C2 AIN
    %% Predecessors: TE/Demand, TE/Staff, TE/Availability, TE/ShiftAverage, TE/Settings
    TE/Role AIN/1 attempt 1 Forecast :task42, 2000-01-01 00:08:41.911, 2000-01-01 00:09:57.071
    %% Predecessors: TE/Demand, TE/Staff, TE/Availability, TE/ShiftAverage, TE/Settings, TE/Role:AIN/1
    TE/Role AIN/2 attempt 1 Forecast :task43, 2000-01-01 00:09:57.071, 2000-01-01 00:11:34.754
    %% Predecessors: TE/Demand, TE/Staff, TE/Availability, TE/ShiftAverage, TE/Settings, TE/Role:AIN/2
    TE/Role AIN/3 attempt 1 Forecast :task44, 2000-01-01 00:11:34.754, 2000-01-01 00:12:54.528
    section TE/C2 RN
    %% Predecessors: TE/Demand, TE/Staff, TE/Availability, TE/ShiftAverage, TE/Settings
    TE/Role RN/1 attempt 1 Forecast :task45, 2000-01-01 00:08:41.911, 2000-01-01 00:09:50.320
    %% Predecessors: TE/Demand, TE/Staff, TE/Availability, TE/ShiftAverage, TE/Settings, TE/Role:RN/1
    TE/Role RN/2 attempt 1 Forecast :task46, 2000-01-01 00:09:50.320, 2000-01-01 00:10:40.944
    %% Predecessors: TE/Demand, TE/Staff, TE/Availability, TE/ShiftAverage, TE/Settings, TE/Role:RN/2
    TE/Role RN/3 attempt 1 Forecast :task47, 2000-01-01 00:10:40.944, 2000-01-01 00:11:44.132
    section TE/C2 EN
    %% Predecessors: TE/Demand, TE/Staff, TE/Availability, TE/ShiftAverage, TE/Settings
    TE/Role EN/1 attempt 1 Forecast :task48, 2000-01-01 00:08:41.911, 2000-01-01 00:09:57.196
    %% Predecessors: TE/Demand, TE/Staff, TE/Availability, TE/ShiftAverage, TE/Settings, TE/Role:EN/1
    TE/Role EN/2 attempt 1 Forecast :task49, 2000-01-01 00:09:57.196, 2000-01-01 00:10:48.788
    %% Predecessors: TE/Demand, TE/Staff, TE/Availability, TE/ShiftAverage, TE/Settings, TE/Role:EN/2
    TE/Role EN/3 attempt 1 Forecast :task50, 2000-01-01 00:10:48.788, 2000-01-01 00:11:50.225
    section TE/U4
    %% Predecessors: TE/Role:AIN/3, TE/Role:EN/3, TE/Role:RN/3, TE/Demand, TE/Staff, TE/Availability, TE/Settings
    TE/Capacity attempt 1 Forecast :task51, 2000-01-01 00:12:54.528, 2000-01-01 00:13:43.290
    %% Predecessors: TE/Capacity, TE/Demand, TE/Allocation, TE/Distribution, TE/MultiRole, TE/Staff, TE/Settings
    TE/Effort attempt 1 Forecast :task52, 2000-01-01 00:13:43.290, 2000-01-01 00:14:27.809
    section JH-RY/A1
    %% Predecessors:
    JH-RY/AllocationInput attempt 1 Forecast :task53, 2000-01-01 00:00:00.000, 2000-01-01 00:00:50.489
    section JH-RY/S1
    %% Predecessors: JH-RY/AllocationInput
    JH-RY/Settings attempt 1 Forecast :task54, 2000-01-01 00:00:50.489, 2000-01-01 00:01:37.045
    section JH-RY/D1
    %% Predecessors: JH-RY/Settings
    JH-RY/DemandMaster attempt 1 Forecast :task55, 2000-01-01 00:01:37.045, 2000-01-01 00:04:40.844
    %% Predecessors: JH-RY/DemandMaster, JH-RY/Settings
    JH-RY/DemandInput attempt 1 Forecast :task56, 2000-01-01 00:04:40.844, 2000-01-01 00:05:32.481
    section JH-RY/C1
    %% Predecessors: JH-RY/AllocationInput, JH-RY/Settings
    JH-RY/Workers attempt 1 Forecast :task57, 2000-01-01 00:01:37.045, 2000-01-01 00:02:41.120
    %% Predecessors: JH-RY/Workers, JH-RY/AllocationInput, JH-RY/Settings
    JH-RY/Availability attempt 1 Forecast :task58, 2000-01-01 00:02:41.120, 2000-01-01 00:05:17.925
    %% Predecessors: JH-RY/Availability, JH-RY/Workers, JH-RY/AllocationInput, JH-RY/Settings
    JH-RY/Staff attempt 1 Forecast :task59, 2000-01-01 00:05:17.925, 2000-01-01 00:06:02.958
    section JH-RY/D2
    %% Predecessors: JH-RY/AllocationInput, JH-RY/DemandInput, JH-RY/Settings
    JH-RY/Intervals attempt 1 Forecast :task60, 2000-01-01 00:05:32.481, 2000-01-01 00:06:18.974
    %% Predecessors: JH-RY/Intervals, JH-RY/DemandInput, JH-RY/Settings
    JH-RY/DemandIntervals attempt 1 Forecast :task61, 2000-01-01 00:06:18.974, 2000-01-01 00:07:07.907
    %% Predecessors: JH-RY/DemandIntervals, JH-RY/Settings
    JH-RY/Demand attempt 1 Forecast :task62, 2000-01-01 00:07:07.907, 2000-01-01 00:07:57.162
    section JH-RY/A2
    %% Predecessors: JH-RY/Intervals, JH-RY/AllocationInput, JH-RY/Settings
    JH-RY/Shifts attempt 1 Forecast :task63, 2000-01-01 00:06:18.974, 2000-01-01 00:08:04.011
    %% Predecessors: JH-RY/Shifts, JH-RY/Settings
    JH-RY/ShiftAverage attempt 1 Forecast :task64, 2000-01-01 00:08:04.011, 2000-01-01 00:09:20.944
    section JH-RY/A3
    %% Predecessors: JH-RY/ShiftAverage, JH-RY/AllocationInput, JH-RY/Settings
    JH-RY/Allocation attempt 1 Forecast :task65, 2000-01-01 00:09:20.944, 2000-01-01 00:10:09.351
    %% Predecessors: JH-RY/Allocation, JH-RY/Settings
    JH-RY/Distribution attempt 1 Forecast :task66, 2000-01-01 00:10:09.351, 2000-01-01 00:11:01.945
    %% Predecessors: JH-RY/Distribution, JH-RY/Settings
    JH-RY/MultiRole attempt 1 Forecast :task67, 2000-01-01 00:11:01.945, 2000-01-01 00:11:51.031
    section JH-RY/C2 AIN
    %% Predecessors: JH-RY/Demand, JH-RY/Staff, JH-RY/Availability, JH-RY/ShiftAverage, JH-RY/Settings
    JH-RY/Role AIN/1 attempt 1 Forecast :task68, 2000-01-01 00:09:20.944, 2000-01-01 00:10:45.257
    %% Predecessors: JH-RY/Demand, JH-RY/Staff, JH-RY/Availability, JH-RY/ShiftAverage, JH-RY/Settings, JH-RY/Role:AIN/1
    JH-RY/Role AIN/2 attempt 1 Forecast :task69, 2000-01-01 00:10:45.257, 2000-01-01 00:11:51.362
    %% Predecessors: JH-RY/Demand, JH-RY/Staff, JH-RY/Availability, JH-RY/ShiftAverage, JH-RY/Settings, JH-RY/Role:AIN/2
    JH-RY/Role AIN/3 attempt 1 Forecast :task70, 2000-01-01 00:11:51.362, 2000-01-01 00:12:49.614
    section JH-RY/C2 RN
    %% Predecessors: JH-RY/Demand, JH-RY/Staff, JH-RY/Availability, JH-RY/ShiftAverage, JH-RY/Settings
    JH-RY/Role RN/1 attempt 1 Forecast :task71, 2000-01-01 00:09:20.944, 2000-01-01 00:10:40.315
    %% Predecessors: JH-RY/Demand, JH-RY/Staff, JH-RY/Availability, JH-RY/ShiftAverage, JH-RY/Settings, JH-RY/Role:RN/1
    JH-RY/Role RN/2 attempt 1 Forecast :task72, 2000-01-01 00:10:40.315, 2000-01-01 00:11:30.597
    %% Predecessors: JH-RY/Demand, JH-RY/Staff, JH-RY/Availability, JH-RY/ShiftAverage, JH-RY/Settings, JH-RY/Role:RN/2
    JH-RY/Role RN/3 attempt 1 Forecast :task73, 2000-01-01 00:11:30.597, 2000-01-01 00:12:25.495
    section JH-RY/C2 EN
    %% Predecessors: JH-RY/Demand, JH-RY/Staff, JH-RY/Availability, JH-RY/ShiftAverage, JH-RY/Settings
    JH-RY/Role EN/1 attempt 1 Forecast :task74, 2000-01-01 00:09:20.944, 2000-01-01 00:10:42.812
    %% Predecessors: JH-RY/Demand, JH-RY/Staff, JH-RY/Availability, JH-RY/ShiftAverage, JH-RY/Settings, JH-RY/Role:EN/1
    JH-RY/Role EN/2 attempt 1 Forecast :task75, 2000-01-01 00:10:42.812, 2000-01-01 00:11:34.292
    %% Predecessors: JH-RY/Demand, JH-RY/Staff, JH-RY/Availability, JH-RY/ShiftAverage, JH-RY/Settings, JH-RY/Role:EN/2
    JH-RY/Role EN/3 attempt 1 Forecast :task76, 2000-01-01 00:11:34.292, 2000-01-01 00:12:30.431
    section JH-RY/U4
    %% Predecessors: JH-RY/Role:AIN/3, JH-RY/Role:EN/3, JH-RY/Role:RN/3, JH-RY/Demand, JH-RY/Staff, JH-RY/Availability, JH-RY/Settings
    JH-RY/Capacity attempt 1 Forecast :task77, 2000-01-01 00:12:49.614, 2000-01-01 00:13:37.074
    %% Predecessors: JH-RY/Capacity, JH-RY/Demand, JH-RY/Allocation, JH-RY/Distribution, JH-RY/MultiRole, JH-RY/Staff, JH-RY/Settings
    JH-RY/Effort attempt 1 Forecast :task78, 2000-01-01 00:13:37.074, 2000-01-01 00:14:21.997
    section Org/O1
    %% Predecessors: BD/Staff, TE/Staff, JH-RY/Staff
    Org/StaffAll attempt 1 Forecast :task79, 2000-01-01 00:07:06.997, 2000-01-01 00:07:47.716
    %% Predecessors: Org/StaffAll, BD/Effort, TE/Effort, JH-RY/Effort
    Org/EffortAll attempt 1 Forecast :task80, 2000-01-01 00:15:32.030, 2000-01-01 00:16:46.583
    section Org/O2
    %% Predecessors: Org/EffortAll, Org/StaffAll
    Org/Outcomes attempt 1 Forecast :task81, 2000-01-01 00:16:46.583, 2000-01-01 00:17:26.699
    %% Predecessors: Org/Outcomes
    Org/Inefficiencies attempt 1 Forecast :task82, 2000-01-01 00:17:26.699, 2000-01-01 00:18:14.849
    section Org/O3
    %% Predecessors: Org/Inefficiencies, Unit1/Settings
    Org/Cost attempt 1 Forecast :task83, 2000-01-01 00:18:14.849, 2000-01-01 00:18:56.901
    section Org/O4
    %% Predecessors: Org/Outcomes
    Org/History attempt 1 Forecast :task84, 2000-01-01 00:17:26.699, 2000-01-01 00:18:09.039
    %% Predecessors: Org/History
    Org/HistoryRead attempt 1 Forecast :task85, 2000-01-01 00:18:09.039, 2000-01-01 00:18:49.469
    section Org/O5
    %% Predecessors: Org/Cost, Org/HistoryRead, Org/Inefficiencies
    Org/Reporting attempt 1 Forecast :task86, 2000-01-01 00:18:56.901, 2000-01-01 00:19:37.342
