gantt
    title Current 20260928-082431-8106f6c4 PartialOrFailed - elapsed 00 00 41 - peak 1
    dateFormat YYYY-MM-DD HH:mm:ss.SSS
    axisFormat %H:%M:%S
    todayMarker off
    section Org/O1
    %% Predecessors: BD/Staff, TE/Staff, JH-RY/Staff
    Org/StaffAll attempt 1 Completed :done, task1, 2000-01-01 00:00:00.582, 2000-01-01 00:00:41.316
    %% Untimed Org/EffortAll; predecessors: Org/StaffAll, BD/Effort, TE/Effort, JH-RY/Effort
    section Org/O2
    %% Untimed Org/Outcomes; predecessors: Org/EffortAll, Org/StaffAll
    %% Untimed Org/Inefficiencies; predecessors: Org/Outcomes
    section Org/O5
    %% Untimed Org/Reporting; predecessors: Org/Cost, Org/HistoryRead, Org/Inefficiencies
