gantt
    title Current 20260925-152017-5cfc6f63 PartialOrFailed - elapsed 00 00 00 - peak 0
    dateFormat YYYY-MM-DD HH:mm:ss.SSS
    axisFormat %H:%M:%S
    todayMarker off
    section Org/O2
    %% Untimed Org/Outcomes; predecessors: Org/EffortAll, Org/StaffAll
    %% Untimed Org/Inefficiencies; predecessors: Org/Outcomes
    section Org/O5
    %% Untimed Org/Reporting; predecessors: Org/Cost, Org/HistoryRead, Org/Inefficiencies
    Report origin :milestone, origin, 2000-01-01 00:00:00.000, 0s
