gantt
    title Current 20260927-155451-7dff5652 Completed - elapsed 00 01 29 - peak 1
    dateFormat YYYY-MM-DD HH:mm:ss.SSS
    axisFormat %H:%M:%S
    todayMarker off
    section TE/U4
    %% Predecessors: TE/Role:AIN/3, TE/Role:EN/3, TE/Role:RN/3, TE/Demand, TE/Staff, TE/Availability, TE/Settings
    TE/Capacity attempt 1 Completed :done, task1, 2000-01-01 00:00:00.411, 2000-01-01 00:00:45.464
    %% Predecessors: TE/Capacity, TE/Demand, TE/Allocation, TE/Distribution, TE/MultiRole, TE/Staff, TE/Settings
    TE/Effort attempt 1 Completed :done, task2, 2000-01-01 00:00:45.501, 2000-01-01 00:01:29.862
