gantt
    title Current 20260927-062412-a365aebd Completed - elapsed 00 02 46 - peak 1
    dateFormat YYYY-MM-DD HH:mm:ss.SSS
    axisFormat %H:%M:%S
    todayMarker off
    section TE/C2 RN
    %% Predecessors: TE/Demand, TE/Staff, TE/Availability, TE/ShiftAverage, TE/Settings
    TE/Role RN/1 attempt 1 Completed :done, task1, 2000-01-01 00:00:00.604, 2000-01-01 00:00:49.730
    %% Predecessors: TE/Demand, TE/Staff, TE/Availability, TE/ShiftAverage, TE/Settings, TE/Role:RN/1
    TE/Role RN/2 attempt 1 Completed :done, task2, 2000-01-01 00:00:49.762, 2000-01-01 00:01:30.886
    %% Predecessors: TE/Demand, TE/Staff, TE/Availability, TE/ShiftAverage, TE/Settings, TE/Role:RN/2
    TE/Role RN/3 attempt 1 Completed :done, task3, 2000-01-01 00:01:30.922, 2000-01-01 00:02:46.889
