gantt
    title Current forecast - elapsed 00 01 29
    dateFormat YYYY-MM-DD HH:mm:ss.SSS
    axisFormat %H:%M:%S
    todayMarker off
    section TE/U4
    %% Predecessors: TE/Role:AIN/3, TE/Role:EN/3, TE/Role:RN/3, TE/Demand, TE/Staff, TE/Availability, TE/Settings
    TE/Capacity attempt 1 Forecast :task1, 2000-01-01 00:00:00.000, 2000-01-01 00:00:46.016
    %% Predecessors: TE/Capacity, TE/Demand, TE/Allocation, TE/Distribution, TE/MultiRole, TE/Staff, TE/Settings
    TE/Effort attempt 1 Forecast :task2, 2000-01-01 00:00:46.016, 2000-01-01 00:01:29.782
