gantt
    title Current forecast - elapsed 00 18 29
    dateFormat YYYY-MM-DD HH:mm:ss.SSS
    axisFormat %H:%M:%S
    todayMarker off
    section Date/D1
    %% Predecessors: BD/Settings, TE/Settings, JH-RY/Settings
    Date/DemandMaster attempt 1 Forecast :task1, 2000-01-01 00:01:40.903, 2000-01-01 00:04:19.069
    section BD/A1
    %% Predecessors:
    BD/AllocationInput attempt 1 Forecast :task2, 2000-01-01 00:00:00.000, 2000-01-01 00:00:49.447
    section BD/S1
    %% Predecessors: BD/AllocationInput
    BD/Settings attempt 1 Forecast :task3, 2000-01-01 00:00:49.447, 2000-01-01 00:01:36.182
    section BD/D1
    %% Predecessors: Date/DemandMaster, BD/Settings
    BD/DemandInput attempt 1 Forecast :task4, 2000-01-01 00:04:19.069, 2000-01-01 00:05:11.914
    section BD/C1
    %% Predecessors: BD/AllocationInput, BD/Settings
    BD/Workers attempt 1 Forecast :task5, 2000-01-01 00:01:36.182, 2000-01-01 00:02:33.786
    %% Predecessors: BD/Workers, BD/AllocationInput, BD/Settings
    BD/Availability attempt 1 Forecast :task6, 2000-01-01 00:02:33.786, 2000-01-01 00:05:45.356
    %% Predecessors: BD/Availability, BD/Workers, BD/AllocationInput, BD/Settings
    BD/Staff attempt 1 Forecast :task7, 2000-01-01 00:05:45.356, 2000-01-01 00:06:31.711
    section BD/D2
    %% Predecessors: BD/AllocationInput, BD/DemandInput, BD/Settings
    BD/Intervals attempt 1 Forecast :task8, 2000-01-01 00:05:11.914, 2000-01-01 00:05:58.470
    %% Predecessors: BD/Intervals, BD/DemandInput, BD/Settings
    BD/DemandIntervals attempt 1 Forecast :task9, 2000-01-01 00:05:58.470, 2000-01-01 00:06:43.731
    %% Predecessors: BD/DemandIntervals, BD/Settings
    BD/Demand attempt 1 Forecast :task10, 2000-01-01 00:06:43.731, 2000-01-01 00:07:31.091
    section BD/A2
    %% Predecessors: BD/Intervals, BD/AllocationInput, BD/Settings
    BD/Shifts attempt 1 Forecast :task11, 2000-01-01 00:05:58.470, 2000-01-01 00:08:08.087
    %% Predecessors: BD/Shifts, BD/Settings
    BD/ShiftAverage attempt 1 Forecast :task12, 2000-01-01 00:08:08.087, 2000-01-01 00:09:09.268
    section BD/A3
    %% Predecessors: BD/ShiftAverage, BD/AllocationInput, BD/Settings
    BD/Allocation attempt 1 Forecast :task13, 2000-01-01 00:09:09.268, 2000-01-01 00:09:51.123
    %% Predecessors: BD/Allocation, BD/Settings
    BD/Distribution attempt 1 Forecast :task14, 2000-01-01 00:09:51.123, 2000-01-01 00:10:33.544
    %% Predecessors: BD/Distribution, BD/Settings
    BD/MultiRole attempt 1 Forecast :task15, 2000-01-01 00:10:33.544, 2000-01-01 00:11:13.683
    section BD/C2 AIN
    %% Predecessors: BD/Demand, BD/Staff, BD/Availability, BD/ShiftAverage, BD/Settings
    BD/Role AIN/1 attempt 1 Forecast :task16, 2000-01-01 00:09:09.268, 2000-01-01 00:10:52.909
    %% Predecessors: BD/Demand, BD/Staff, BD/Availability, BD/ShiftAverage, BD/Settings, BD/Role:AIN/1
    BD/Role AIN/2 attempt 1 Forecast :task17, 2000-01-01 00:10:52.909, 2000-01-01 00:11:43.946
    %% Predecessors: BD/Demand, BD/Staff, BD/Availability, BD/ShiftAverage, BD/Settings, BD/Role:AIN/2
    BD/Role AIN/3 attempt 1 Forecast :task18, 2000-01-01 00:11:43.946, 2000-01-01 00:12:55.254
    section BD/C2 RN
    %% Predecessors: BD/Demand, BD/Staff, BD/Availability, BD/ShiftAverage, BD/Settings
    BD/Role RN/1 attempt 1 Forecast :task19, 2000-01-01 00:09:09.268, 2000-01-01 00:10:40.560
    %% Predecessors: BD/Demand, BD/Staff, BD/Availability, BD/ShiftAverage, BD/Settings, BD/Role:RN/1
    BD/Role RN/2 attempt 1 Forecast :task20, 2000-01-01 00:10:40.560, 2000-01-01 00:11:28.254
    %% Predecessors: BD/Demand, BD/Staff, BD/Availability, BD/ShiftAverage, BD/Settings, BD/Role:RN/2
    BD/Role RN/3 attempt 1 Forecast :task21, 2000-01-01 00:11:28.254, 2000-01-01 00:12:18.070
    section BD/C2 EN
    %% Predecessors: BD/Demand, BD/Staff, BD/Availability, BD/ShiftAverage, BD/Settings
    BD/Role EN/1 attempt 1 Forecast :task22, 2000-01-01 00:09:09.268, 2000-01-01 00:10:41.024
    %% Predecessors: BD/Demand, BD/Staff, BD/Availability, BD/ShiftAverage, BD/Settings, BD/Role:EN/1
    BD/Role EN/2 attempt 1 Forecast :task23, 2000-01-01 00:10:41.024, 2000-01-01 00:11:29.434
    %% Predecessors: BD/Demand, BD/Staff, BD/Availability, BD/ShiftAverage, BD/Settings, BD/Role:EN/2
    BD/Role EN/3 attempt 1 Forecast :task24, 2000-01-01 00:11:29.434, 2000-01-01 00:12:20.015
    section BD/U4
    %% Predecessors: BD/Role:AIN/3, BD/Role:EN/3, BD/Role:RN/3, BD/Demand, BD/Staff, BD/Availability, BD/Settings
    BD/Capacity attempt 1 Forecast :task25, 2000-01-01 00:12:55.254, 2000-01-01 00:13:40.331
    %% Predecessors: BD/Capacity, BD/Demand, BD/Allocation, BD/Distribution, BD/MultiRole, BD/Staff, BD/Settings
    BD/Effort attempt 1 Forecast :task26, 2000-01-01 00:13:40.331, 2000-01-01 00:14:24.954
    section TE/A1
    %% Predecessors:
    TE/AllocationInput attempt 1 Forecast :task27, 2000-01-01 00:00:00.000, 2000-01-01 00:00:53.005
    section TE/S1
    %% Predecessors: TE/AllocationInput
    TE/Settings attempt 1 Forecast :task28, 2000-01-01 00:00:53.005, 2000-01-01 00:01:40.903
    section TE/D1
    %% Predecessors: Date/DemandMaster, TE/Settings
    TE/DemandInput attempt 1 Forecast :task29, 2000-01-01 00:04:19.069, 2000-01-01 00:05:13.935
    section TE/C1
    %% Predecessors: TE/AllocationInput, TE/Settings
    TE/Workers attempt 1 Forecast :task30, 2000-01-01 00:01:40.903, 2000-01-01 00:02:46.811
    %% Predecessors: TE/Workers, TE/AllocationInput, TE/Settings
    TE/Availability attempt 1 Forecast :task31, 2000-01-01 00:02:46.811, 2000-01-01 00:04:54.586
    %% Predecessors: TE/Availability, TE/Workers, TE/AllocationInput, TE/Settings
    TE/Staff attempt 1 Forecast :task32, 2000-01-01 00:04:54.586, 2000-01-01 00:05:44.418
    section TE/D2
    %% Predecessors: TE/AllocationInput, TE/DemandInput, TE/Settings
    TE/Intervals attempt 1 Forecast :task33, 2000-01-01 00:05:13.935, 2000-01-01 00:06:01.557
    %% Predecessors: TE/Intervals, TE/DemandInput, TE/Settings
    TE/DemandIntervals attempt 1 Forecast :task34, 2000-01-01 00:06:01.557, 2000-01-01 00:06:46.219
    %% Predecessors: TE/DemandIntervals, TE/Settings
    TE/Demand attempt 1 Forecast :task35, 2000-01-01 00:06:46.219, 2000-01-01 00:07:34.039
    section TE/A2
    %% Predecessors: TE/Intervals, TE/AllocationInput, TE/Settings
    TE/Shifts attempt 1 Forecast :task36, 2000-01-01 00:06:01.557, 2000-01-01 00:07:15.622
    %% Predecessors: TE/Shifts, TE/Settings
    TE/ShiftAverage attempt 1 Forecast :task37, 2000-01-01 00:07:15.622, 2000-01-01 00:08:17.590
    section TE/A3
    %% Predecessors: TE/ShiftAverage, TE/AllocationInput, TE/Settings
    TE/Allocation attempt 1 Forecast :task38, 2000-01-01 00:08:17.590, 2000-01-01 00:08:59.141
    %% Predecessors: TE/Allocation, TE/Settings
    TE/Distribution attempt 1 Forecast :task39, 2000-01-01 00:08:59.141, 2000-01-01 00:09:41.987
    %% Predecessors: TE/Distribution, TE/Settings
    TE/MultiRole attempt 1 Forecast :task40, 2000-01-01 00:09:41.987, 2000-01-01 00:10:22.657
    section TE/C2 AIN
    %% Predecessors: TE/Demand, TE/Staff, TE/Availability, TE/ShiftAverage, TE/Settings
    TE/Role AIN/1 attempt 1 Forecast :task41, 2000-01-01 00:08:17.590, 2000-01-01 00:09:33.259
    %% Predecessors: TE/Demand, TE/Staff, TE/Availability, TE/ShiftAverage, TE/Settings, TE/Role:AIN/1
    TE/Role AIN/2 attempt 1 Forecast :task42, 2000-01-01 00:09:33.259, 2000-01-01 00:11:13.987
    %% Predecessors: TE/Demand, TE/Staff, TE/Availability, TE/ShiftAverage, TE/Settings, TE/Role:AIN/2
    TE/Role AIN/3 attempt 1 Forecast :task43, 2000-01-01 00:11:13.987, 2000-01-01 00:12:33.107
    section TE/C2 RN
    %% Predecessors: TE/Demand, TE/Staff, TE/Availability, TE/ShiftAverage, TE/Settings
    TE/Role RN/1 attempt 1 Forecast :task44, 2000-01-01 00:08:17.590, 2000-01-01 00:09:27.898
    %% Predecessors: TE/Demand, TE/Staff, TE/Availability, TE/ShiftAverage, TE/Settings, TE/Role:RN/1
    TE/Role RN/2 attempt 1 Forecast :task45, 2000-01-01 00:09:27.898, 2000-01-01 00:10:20.289
    %% Predecessors: TE/Demand, TE/Staff, TE/Availability, TE/ShiftAverage, TE/Settings, TE/Role:RN/2
    TE/Role RN/3 attempt 1 Forecast :task46, 2000-01-01 00:10:20.289, 2000-01-01 00:11:21.108
    section TE/C2 EN
    %% Predecessors: TE/Demand, TE/Staff, TE/Availability, TE/ShiftAverage, TE/Settings
    TE/Role EN/1 attempt 1 Forecast :task47, 2000-01-01 00:08:17.590, 2000-01-01 00:09:30.106
    %% Predecessors: TE/Demand, TE/Staff, TE/Availability, TE/ShiftAverage, TE/Settings, TE/Role:EN/1
    TE/Role EN/2 attempt 1 Forecast :task48, 2000-01-01 00:09:30.106, 2000-01-01 00:10:20.226
    %% Predecessors: TE/Demand, TE/Staff, TE/Availability, TE/ShiftAverage, TE/Settings, TE/Role:EN/2
    TE/Role EN/3 attempt 1 Forecast :task49, 2000-01-01 00:10:20.226, 2000-01-01 00:11:24.095
    section TE/U4
    %% Predecessors: TE/Role:AIN/3, TE/Role:EN/3, TE/Role:RN/3, TE/Demand, TE/Staff, TE/Availability, TE/Settings
    TE/Capacity attempt 1 Forecast :task50, 2000-01-01 00:12:33.107, 2000-01-01 00:13:18.999
    %% Predecessors: TE/Capacity, TE/Demand, TE/Allocation, TE/Distribution, TE/MultiRole, TE/Staff, TE/Settings
    TE/Effort attempt 1 Forecast :task51, 2000-01-01 00:13:18.999, 2000-01-01 00:14:03.805
    section JH-RY/A1
    %% Predecessors:
    JH-RY/AllocationInput attempt 1 Forecast :task52, 2000-01-01 00:00:00.000, 2000-01-01 00:00:51.827
    section JH-RY/S1
    %% Predecessors: JH-RY/AllocationInput
    JH-RY/Settings attempt 1 Forecast :task53, 2000-01-01 00:00:51.827, 2000-01-01 00:01:39.484
    section JH-RY/D1
    %% Predecessors: Date/DemandMaster, JH-RY/Settings
    JH-RY/DemandInput attempt 1 Forecast :task54, 2000-01-01 00:04:19.069, 2000-01-01 00:05:15.966
    section JH-RY/C1
    %% Predecessors: JH-RY/AllocationInput, JH-RY/Settings
    JH-RY/Workers attempt 1 Forecast :task55, 2000-01-01 00:01:39.484, 2000-01-01 00:02:40.864
    %% Predecessors: JH-RY/Workers, JH-RY/AllocationInput, JH-RY/Settings
    JH-RY/Availability attempt 1 Forecast :task56, 2000-01-01 00:02:40.864, 2000-01-01 00:04:52.044
    %% Predecessors: JH-RY/Availability, JH-RY/Workers, JH-RY/AllocationInput, JH-RY/Settings
    JH-RY/Staff attempt 1 Forecast :task57, 2000-01-01 00:04:52.044, 2000-01-01 00:05:40.131
    section JH-RY/D2
    %% Predecessors: JH-RY/AllocationInput, JH-RY/DemandInput, JH-RY/Settings
    JH-RY/Intervals attempt 1 Forecast :task58, 2000-01-01 00:05:15.966, 2000-01-01 00:06:04.946
    %% Predecessors: JH-RY/Intervals, JH-RY/DemandInput, JH-RY/Settings
    JH-RY/DemandIntervals attempt 1 Forecast :task59, 2000-01-01 00:06:04.946, 2000-01-01 00:06:54.266
    %% Predecessors: JH-RY/DemandIntervals, JH-RY/Settings
    JH-RY/Demand attempt 1 Forecast :task60, 2000-01-01 00:06:54.266, 2000-01-01 00:07:43.650
    section JH-RY/A2
    %% Predecessors: JH-RY/Intervals, JH-RY/AllocationInput, JH-RY/Settings
    JH-RY/Shifts attempt 1 Forecast :task61, 2000-01-01 00:06:04.946, 2000-01-01 00:07:41.373
    %% Predecessors: JH-RY/Shifts, JH-RY/Settings
    JH-RY/ShiftAverage attempt 1 Forecast :task62, 2000-01-01 00:07:41.373, 2000-01-01 00:08:44.519
    section JH-RY/A3
    %% Predecessors: JH-RY/ShiftAverage, JH-RY/AllocationInput, JH-RY/Settings
    JH-RY/Allocation attempt 1 Forecast :task63, 2000-01-01 00:08:44.519, 2000-01-01 00:09:26.484
    %% Predecessors: JH-RY/Allocation, JH-RY/Settings
    JH-RY/Distribution attempt 1 Forecast :task64, 2000-01-01 00:09:26.484, 2000-01-01 00:10:09.305
    %% Predecessors: JH-RY/Distribution, JH-RY/Settings
    JH-RY/MultiRole attempt 1 Forecast :task65, 2000-01-01 00:10:09.305, 2000-01-01 00:10:49.712
    section JH-RY/C2 AIN
    %% Predecessors: JH-RY/Demand, JH-RY/Staff, JH-RY/Availability, JH-RY/ShiftAverage, JH-RY/Settings
    JH-RY/Role AIN/1 attempt 1 Forecast :task66, 2000-01-01 00:08:44.519, 2000-01-01 00:10:07.402
    %% Predecessors: JH-RY/Demand, JH-RY/Staff, JH-RY/Availability, JH-RY/ShiftAverage, JH-RY/Settings, JH-RY/Role:AIN/1
    JH-RY/Role AIN/2 attempt 1 Forecast :task67, 2000-01-01 00:10:07.402, 2000-01-01 00:11:14.566
    %% Predecessors: JH-RY/Demand, JH-RY/Staff, JH-RY/Availability, JH-RY/ShiftAverage, JH-RY/Settings, JH-RY/Role:AIN/2
    JH-RY/Role AIN/3 attempt 1 Forecast :task68, 2000-01-01 00:11:14.566, 2000-01-01 00:12:14.295
    section JH-RY/C2 RN
    %% Predecessors: JH-RY/Demand, JH-RY/Staff, JH-RY/Availability, JH-RY/ShiftAverage, JH-RY/Settings
    JH-RY/Role RN/1 attempt 1 Forecast :task69, 2000-01-01 00:08:44.519, 2000-01-01 00:10:10.360
    %% Predecessors: JH-RY/Demand, JH-RY/Staff, JH-RY/Availability, JH-RY/ShiftAverage, JH-RY/Settings, JH-RY/Role:RN/1
    JH-RY/Role RN/2 attempt 1 Forecast :task70, 2000-01-01 00:10:10.360, 2000-01-01 00:11:07.230
    %% Predecessors: JH-RY/Demand, JH-RY/Staff, JH-RY/Availability, JH-RY/ShiftAverage, JH-RY/Settings, JH-RY/Role:RN/2
    JH-RY/Role RN/3 attempt 1 Forecast :task71, 2000-01-01 00:11:07.230, 2000-01-01 00:12:00.389
    section JH-RY/C2 EN
    %% Predecessors: JH-RY/Demand, JH-RY/Staff, JH-RY/Availability, JH-RY/ShiftAverage, JH-RY/Settings
    JH-RY/Role EN/1 attempt 1 Forecast :task72, 2000-01-01 00:08:44.519, 2000-01-01 00:10:13.768
    %% Predecessors: JH-RY/Demand, JH-RY/Staff, JH-RY/Availability, JH-RY/ShiftAverage, JH-RY/Settings, JH-RY/Role:EN/1
    JH-RY/Role EN/2 attempt 1 Forecast :task73, 2000-01-01 00:10:13.768, 2000-01-01 00:11:09.068
    %% Predecessors: JH-RY/Demand, JH-RY/Staff, JH-RY/Availability, JH-RY/ShiftAverage, JH-RY/Settings, JH-RY/Role:EN/2
    JH-RY/Role EN/3 attempt 1 Forecast :task74, 2000-01-01 00:11:09.068, 2000-01-01 00:12:02.006
    section JH-RY/U4
    %% Predecessors: JH-RY/Role:AIN/3, JH-RY/Role:EN/3, JH-RY/Role:RN/3, JH-RY/Demand, JH-RY/Staff, JH-RY/Availability, JH-RY/Settings
    JH-RY/Capacity attempt 1 Forecast :task75, 2000-01-01 00:12:14.295, 2000-01-01 00:13:02.391
    %% Predecessors: JH-RY/Capacity, JH-RY/Demand, JH-RY/Allocation, JH-RY/Distribution, JH-RY/MultiRole, JH-RY/Staff, JH-RY/Settings
    JH-RY/Effort attempt 1 Forecast :task76, 2000-01-01 00:13:02.391, 2000-01-01 00:13:46.981
    section Org/O1
    %% Predecessors: BD/Staff, TE/Staff, JH-RY/Staff
    Org/StaffAll attempt 1 Forecast :task77, 2000-01-01 00:06:31.711, 2000-01-01 00:07:15.798
    %% Predecessors: Org/StaffAll, BD/Effort, TE/Effort, JH-RY/Effort
    Org/EffortAll attempt 1 Forecast :task78, 2000-01-01 00:14:24.954, 2000-01-01 00:15:35.761
    section Org/O2
    %% Predecessors: Org/EffortAll, Org/StaffAll
    Org/Outcomes attempt 1 Forecast :task79, 2000-01-01 00:15:35.761, 2000-01-01 00:16:16.356
    %% Predecessors: Org/Outcomes
    Org/Inefficiencies attempt 1 Forecast :task80, 2000-01-01 00:16:16.356, 2000-01-01 00:17:05.835
    section Org/O3
    %% Predecessors: Org/Inefficiencies, Unit1/Settings
    Org/Cost attempt 1 Forecast :task81, 2000-01-01 00:17:05.835, 2000-01-01 00:17:47.855
    section Org/O4
    %% Predecessors: Org/Outcomes
    Org/History attempt 1 Forecast :task82, 2000-01-01 00:16:16.356, 2000-01-01 00:16:59.090
    %% Predecessors: Org/History
    Org/HistoryRead attempt 1 Forecast :task83, 2000-01-01 00:16:59.090, 2000-01-01 00:17:39.751
    section Org/O5
    %% Predecessors: Org/Cost, Org/HistoryRead, Org/Inefficiencies
    Org/Reporting attempt 1 Forecast :task84, 2000-01-01 00:17:47.855, 2000-01-01 00:18:29.063
