gantt
    title ParallelInputs-Unit1Priority forecast - elapsed 00 10 52
    dateFormat YYYY-MM-DD HH:mm:ss.SSS
    axisFormat %H:%M:%S
    todayMarker off
    section Unit1/A1
    %% Predecessors:
    Unit1/AllocationInput attempt 1 Forecast :task1, 2000-01-01 00:00:00.000, 2000-01-01 00:01:56.319
    section Unit1/S1
    %% Predecessors:
    Unit1/Settings attempt 1 Forecast :task2, 2000-01-01 00:00:00.000, 2000-01-01 00:00:39.044
    section Unit1/D1
    %% Predecessors:
    Unit1/DemandMaster attempt 1 Forecast :task3, 2000-01-01 00:00:00.000, 2000-01-01 00:02:50.895
    %% Predecessors: Unit1/DemandMaster
    Unit1/DemandInput attempt 1 Forecast :task4, 2000-01-01 00:02:50.895, 2000-01-01 00:03:30.984
    section Unit1/C1
    %% Predecessors: Unit1/AllocationInput, Unit1/Settings
    Unit1/Workers attempt 1 Forecast :task5, 2000-01-01 00:01:56.319, 2000-01-01 00:02:39.402
    %% Predecessors: Unit1/Workers, Unit1/AllocationInput, Unit1/Settings
    Unit1/Availability attempt 1 Forecast :task6, 2000-01-01 00:02:39.402, 2000-01-01 00:03:38.576
    %% Predecessors: Unit1/Availability, Unit1/Workers, Unit1/AllocationInput, Unit1/Settings
    Unit1/Staff attempt 1 Forecast :task7, 2000-01-01 00:03:38.576, 2000-01-01 00:04:21.071
    section Unit1/D2
    %% Predecessors: Unit1/AllocationInput, Unit1/DemandInput, Unit1/Settings
    Unit1/Intervals attempt 1 Forecast :task8, 2000-01-01 00:03:30.984, 2000-01-01 00:04:11.747
    %% Predecessors: Unit1/Intervals, Unit1/DemandInput, Unit1/Settings
    Unit1/DemandIntervals attempt 1 Forecast :task9, 2000-01-01 00:04:11.747, 2000-01-01 00:04:52.558
    %% Predecessors: Unit1/DemandIntervals, Unit1/Settings
    Unit1/Demand attempt 1 Forecast :task10, 2000-01-01 00:04:52.558, 2000-01-01 00:05:34.750
    section Unit1/A2
    %% Predecessors: Unit1/Intervals, Unit1/AllocationInput, Unit1/Settings
    Unit1/Shifts attempt 1 Forecast :task11, 2000-01-01 00:04:11.747, 2000-01-01 00:06:07.811
    %% Predecessors: Unit1/Shifts, Unit1/Settings
    Unit1/ShiftAverage attempt 1 Forecast :task12, 2000-01-01 00:06:07.811, 2000-01-01 00:07:04.675
    section Unit1/A3
    %% Predecessors: Unit1/ShiftAverage, Unit1/AllocationInput, Unit1/Settings
    Unit1/Allocation attempt 1 Forecast :task13, 2000-01-01 00:07:04.675, 2000-01-01 00:07:45.208
    %% Predecessors: Unit1/Allocation, Unit1/Settings
    Unit1/Distribution attempt 1 Forecast :task14, 2000-01-01 00:07:45.208, 2000-01-01 00:08:27.340
    %% Predecessors: Unit1/Distribution, Unit1/Settings
    Unit1/MultiRole attempt 1 Forecast :task15, 2000-01-01 00:08:27.340, 2000-01-01 00:09:06.840
    section Unit1/C2 AIN
    %% Predecessors: Unit1/Demand, Unit1/Staff, Unit1/Availability, Unit1/ShiftAverage, Unit1/Settings
    Unit1/Role AIN/1 attempt 1 Forecast :task16, 2000-01-01 00:07:04.675, 2000-01-01 00:07:53.233
    %% Predecessors: Unit1/Demand, Unit1/Staff, Unit1/Availability, Unit1/ShiftAverage, Unit1/Settings, Unit1/Role:AIN/1
    Unit1/Role AIN/2 attempt 1 Forecast :task17, 2000-01-01 00:07:53.233, 2000-01-01 00:08:40.037
    %% Predecessors: Unit1/Demand, Unit1/Staff, Unit1/Availability, Unit1/ShiftAverage, Unit1/Settings, Unit1/Role:AIN/2
    Unit1/Role AIN/3 attempt 1 Forecast :task18, 2000-01-01 00:08:40.037, 2000-01-01 00:09:26.695
    section Unit1/C2 AINC4
    %% Predecessors: Unit1/Demand, Unit1/Staff, Unit1/Availability, Unit1/ShiftAverage, Unit1/Settings
    Unit1/Role AINC4/1 attempt 1 Forecast :task19, 2000-01-01 00:07:04.675, 2000-01-01 00:07:52.920
    %% Predecessors: Unit1/Demand, Unit1/Staff, Unit1/Availability, Unit1/ShiftAverage, Unit1/Settings, Unit1/Role:AINC4/1
    Unit1/Role AINC4/2 attempt 1 Forecast :task20, 2000-01-01 00:07:52.920, 2000-01-01 00:08:35.708
    %% Predecessors: Unit1/Demand, Unit1/Staff, Unit1/Availability, Unit1/ShiftAverage, Unit1/Settings, Unit1/Role:AINC4/2
    Unit1/Role AINC4/3 attempt 1 Forecast :task21, 2000-01-01 00:08:35.708, 2000-01-01 00:09:20.279
    section Unit1/C2 RN
    %% Predecessors: Unit1/Demand, Unit1/Staff, Unit1/Availability, Unit1/ShiftAverage, Unit1/Settings
    Unit1/Role RN/1 attempt 1 Forecast :task22, 2000-01-01 00:07:04.675, 2000-01-01 00:07:52.738
    %% Predecessors: Unit1/Demand, Unit1/Staff, Unit1/Availability, Unit1/ShiftAverage, Unit1/Settings, Unit1/Role:RN/1
    Unit1/Role RN/2 attempt 1 Forecast :task23, 2000-01-01 00:07:52.738, 2000-01-01 00:08:34.891
    %% Predecessors: Unit1/Demand, Unit1/Staff, Unit1/Availability, Unit1/ShiftAverage, Unit1/Settings, Unit1/Role:RN/2
    Unit1/Role RN/3 attempt 1 Forecast :task24, 2000-01-01 00:08:34.891, 2000-01-01 00:09:17.243
    section Unit1/U4
    %% Predecessors: Unit1/Role:AIN/3, Unit1/Role:AINC4/3, Unit1/Role:RN/3, Unit1/Demand, Unit1/Staff, Unit1/Availability, Unit1/Settings
    Unit1/Capacity attempt 1 Forecast :task25, 2000-01-01 00:09:26.695, 2000-01-01 00:10:07.370
    %% Predecessors: Unit1/Capacity, Unit1/Demand, Unit1/Allocation, Unit1/Distribution, Unit1/MultiRole, Unit1/Staff, Unit1/Settings
    Unit1/Effort attempt 1 Forecast :task26, 2000-01-01 00:10:07.370, 2000-01-01 00:10:52.400
